apiVersion: v1
kind: PersistentVolume
metadata:
  name: landing-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {project name}
    name: landing-pvc
  hostPath:
    path: /mnt/landing-data  # Ensure this path exists on the host node
